package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {

	// handle `/` route
	http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
		html := `
<!doctype html>
<title>web.go</title>
Hello World! (from GoLang's net/http)<br>
...
`
		fmt.Fprint(res, html)
	})

	// run server on port 443=https 80=http

	// your DNS domain is not netop.info so change below accordingly
	// these 2 files were generated by certbot
	// https://golang.org/pkg/net/http/#ListenAndServeTLS

	certFile := "/etc/letsencrypt/live/netop.info/fullchain.pem"
	keyFile := "/etc/letsencrypt/live/netop.info/privkey.pem"
	serverError := http.ListenAndServeTLS(":443", certFile, keyFile, nil)
	log.Fatal(serverError)

}
